project:
  type: book

lang: en

execute:
  freeze: auto
  echo: false
  warning: false

book:
  title: "Python Enterprise CRUD Demo"
  subtitle: "B2B Discount Maintenance with MSSQL and Streamlit"
  search:
    type: overlay
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2026

  chapters:
    - index.qmd
    - part: "Preparation"
      chapters:
        - accounts.qmd
        - windows-setup.qmd
        - mac-setup.qmd
    - part: "MSSQL"
      chapters:
        - mssql-vscode.qmd
        - mssql-connection.qmd
        - mssql-example.qmd
    - part: "Application"
      chapters:
        - streamlit.qmd

number-sections: true

format:
  html:
    toc: true
    theme:
      - cosmo
      - theme.scss
    code-copy: true
    highlight-style: github
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple
    include-in-header:
      text: |
        <style>
        .cmd-explain {
          font-weight: 600;
          margin-top: 1rem;
        }
        </style>
